spring:
   profiles:
      active:
        - dev
---
server:
  port: 8201

spring:
  profiles: dev
  application:
      name: cloudconfig-test-client123

eureka:
 client:
  serviceUrl:
    defaultZone: http://admin:enjoy@localhost:7301/eureka
  register-with-eureka: false

info:
  app.name: springcloud-config-client-dev123
  company.name: enjoy123
---
server:
  port: 8102

spring:
  profiles: beta
  application:
      name: cloudconfig-test-client321

eureka:
 client:
  serviceUrl:
    defaultZone: http://admin:enjoy@localhost:7301/eureka
  register-with-eureka: false
  
info:
  app.name: springcloud-config-client-beta321
  company.name: enjoy321